# This is a Docker Compose file for server with monitoring tools.

services:
  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - "prometheus_data:/prometheus"
      - "./prometheus:/etc/prometheus:ro"
      - "/etc/hosts:/etc/hosts:ro"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.retention.size=4GB"

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
    environment:
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-http://localhost:3000/grafana}

  loki:
    image: grafana/loki:3.0.0
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - "./loki:/etc/loki"
    command: -config.file=/etc/loki/loki-config.yaml

  alertmanager:
    image: "prom/alertmanager:v0.27.0"
    container_name: alertmanager
    restart: always
    volumes:
      - "./alertmanager/:/etc/alertmanager/"
    ports:
      - "9093:9093"
    command:
      - "--config.file=/etc/alertmanager/alertmanager-config.yaml"
      - "--storage.path=/alertmanager"

volumes:
  prometheus_data:
  grafana_data:
