$schema: https://json-schema.org/draft-07/schema
$defs:
  RepositoryConfig:
    additionalProperties: false
    properties:
      deploy_script:
        anyOf:
        - format: path
          type: string
        - type: 'null'
        default: null
        title: Deploy Script
      static_dir:
        anyOf:
        - format: path
          type: string
        - type: 'null'
        default: null
        title: Static Dir
    title: RepositoryConfig
    type: object
additionalProperties: false
properties:
  $schema:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: $Schema
  webhook_secret:
    title: Webhook Secret
    type: string
  app_root_path:
    default: ''
    title: App Root Path
    type: string
  repositories:
    additionalProperties:
      $ref: '#/$defs/RepositoryConfig'
    title: Repositories
    type: object
required:
- webhook_secret
- repositories
title: Settings
type: object
