$schema: ./settings.schema.yaml

webhook_secret: change-me
app_root_path: ""

repositories:
  one-zero-eight/monorepo:
    deploy_script: /srv/innohassle/monorepo/deploy.sh

  one-zero-eight/website:
    pre:
      static_dir: /var/www/website-pre
    production:
      static_dir: /var/www/website-production
